### ISSUE TITLE
Add some nice data to the server

### ISSUE THREAD

**Issue by ovnora** [tortelio/timeseries#6]
* at least 3 timeseries
* at least 1 timeseries, where the derivated values have meaning (e.g movement)
* at least 2 correspondig timeseries (same dimensions)
* at least 2 timeseries with different dimension (at least 1 different dimension)

**Comment by ovnora** [comment]
+ long timeseries for testing (can be generated)

**Comment by tortelio** [comment]
FYI There are some files on `data` branch to try out. To making the CLI more friendlier is still missing.

**Comment by tortelio** [comment]
Example data is merged into `master`.

**Comment by tortelio** [comment]
With the following lines you can try it out:
```shell
# in bash 1
make shell
````
```shell
# in bash 2
make build
./timeseries_cli --upload filename
```

**Comment by ovnora** [comment]
Please change values in humidity data from string to number.
