### ISSUE TITLE
Clean up and merge all the existing code

### ISSUE THREAD

**Issue by tortelio** [tortelio/timeseries#9]

**Comment by ovnora** [comment]
Clean up. Changed Makefile as discussed. Should I merged it into dev branch?

**Comment by tortelio** [comment]
No, I will try to merge all of my code.

**Comment by tortelio** [comment]
Please check `dev` branch. Did I rebase properly?

**Comment by ovnora** [comment]
Few mistakes:
- You didn't change the paths in timeseries_app.erl (fixed it)
- There is still a timeseries/priv directory. Do we need it?
FYI: I added a few minor chages to the client (pushed to 'dev' branch)
